"""Detect hallucinated references to Drifter commands and MCP tools in docs."""

from __future__ import annotations

import ast
import json
import re
from pathlib import Path

from drifter.checks._base import Issue
from drifter.config import Config


def _load_manifest(root: Path) -> dict | None:
    manifest_path = root / ".drifter" / "capability-manifest.json"
    if manifest_path.exists():
        try:
            return json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            return None
    return None


def _generate_manifest(root: Path) -> dict | None:
    try:
        from drifter.manifest_generator import generate_manifest

        cap = generate_manifest(root)
        if hasattr(cap, "to_dict"):
            return cap.to_dict()
        return cap if isinstance(cap, dict) else None
    except Exception:
        return None


def _get_valid_commands(manifest: dict) -> set[str]:
    return {cmd["name"] for cmd in manifest.get("commands", [])}


def _get_valid_mcp_tools(manifest: dict) -> set[str]:
    return {tool["name"] for tool in manifest.get("mcp_tools", [])}


def _running_drifter_commands() -> set[str]:
    """Command names from the installed Drifter package's own cli.py.

    A project's capability manifest describes the PROJECT, so adopting
    projects (no src/drifter/cli.py) have an empty command list — without
    this union, every `drifter check` mention in their docs is a false
    positive they cannot fix.
    """
    try:
        import drifter.cli

        cli_file = Path(drifter.cli.__file__ or "")
        tree = ast.parse(cli_file.read_text(encoding="utf-8"))
        return {
            str(node.args[0].value)
            for node in ast.walk(tree)
            if isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "add_parser"
            and node.args
            and isinstance(node.args[0], ast.Constant)
        }
    except Exception:
        return set()


# Patterns that look like drifter command references
_RE_DRIFTER_CMD = re.compile(r"`drifter\s+(\w+)`")
_RE_MCP_TOOL = re.compile(r"\b(drifter_\w+)\b")
_RE_FRONTMATTER = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)
_RE_STATUS_DRAFT = re.compile(r"^status:\s*['\"]?draft\b", re.IGNORECASE | re.MULTILINE)


def _is_draft(text: str) -> bool:
    """True if the document's frontmatter marks it as a draft.

    Draft docs (e.g. SOWs) legitimately reference PROPOSED commands and
    tools that do not exist yet.
    """
    match = _RE_FRONTMATTER.match(text)
    return bool(match and _RE_STATUS_DRAFT.search(match.group(1)))


class GhostReferenceCheck:
    """Scan markdown docs for references to non-existent commands or MCP tools."""

    name = "ghost_reference"

    def run(self, root: Path, config: Config) -> list[Issue]:
        issues: list[Issue] = []

        manifest = _load_manifest(root)
        # An on-disk manifest may be stale (generated by an older Drifter);
        # a freshly generated one reflects the code as it stands.
        from_disk = manifest is not None
        if manifest is None:
            manifest = _generate_manifest(root)
        if manifest is None:
            return issues

        hint = (
            " (not in .drifter/capability-manifest.json — "
            "if the command exists, regenerate with `drifter manifest`)"
            if from_disk
            else ""
        )

        valid_commands = _get_valid_commands(manifest) | _running_drifter_commands()
        valid_mcp_tools = _get_valid_mcp_tools(manifest)

        # root.rglob("*.md") already includes root-level docs like README.md
        md_files = sorted(root.rglob("*.md"))

        reported: set[tuple[str, str]] = set()

        for md_file in md_files:
            if config.is_check_ignored(self.name, md_file):
                continue
            # Archive files are historical records; they may reference
            # commands that were renamed or removed since
            if "docs/archive" in str(md_file):
                continue
            try:
                text = md_file.read_text(encoding="utf-8")
            except Exception:
                continue
            if _is_draft(text):
                continue

            rel = str(md_file.relative_to(root))

            for lineno, line in enumerate(text.split("\n"), start=1):
                # Check drifter command references (backtick inline)
                for match in _RE_DRIFTER_CMD.finditer(line):
                    cmd = match.group(1)
                    if cmd in valid_commands or (rel, cmd) in reported:
                        continue
                    reported.add((rel, cmd))
                    issues.append(
                        Issue(
                            check=self.name,
                            file=rel,
                            detail=f"line {lineno}: referenced command `drifter {cmd}` does not exist{hint}",
                            severity="warn",
                        )
                    )

                # Check MCP tool references
                for match in _RE_MCP_TOOL.finditer(line):
                    tool = match.group(1)
                    if tool in valid_mcp_tools or (rel, tool) in reported:
                        continue
                    reported.add((rel, tool))
                    issues.append(
                        Issue(
                            check=self.name,
                            file=rel,
                            detail=f"line {lineno}: referenced MCP tool `{tool}` does not exist{hint}",
                            severity="warn",
                        )
                    )

        return issues
