"""CLI handlers for `drifter init` and `drifter validate`."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

from drifter._cli_common import print_banner, print_rule
from drifter._templates import template_text
from drifter.config import Config
from drifter.doc_validator import validate_docs


def _doc_stub(title: str, doc_type: str, phase: str, now: str) -> str:
    """Generate a minimal doc stub with correct frontmatter."""
    return f"""---
title: {title}
type: {doc_type}
version: "1.0"
status: active
phase: {phase}
created: '{now}'
updated: '{now}'
---

# {title}

> **TODO**: Fill in this document. This is a stub generated by `drifter init --full`.

*(Add your content here.)*
"""


def cmd_init(args: argparse.Namespace) -> int:
    root = Path(args.root or ".").resolve()
    root.mkdir(parents=True, exist_ok=True)

    # Create docs directory
    docs_dir = root / "docs"
    digests_dir = docs_dir / "digests"
    digests_dir.mkdir(parents=True, exist_ok=True)
    archive_dir = docs_dir / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)

    # Core files always come from the bundled templates
    template_files: dict[Path, str] = {
        root / "AGENTS.md": "AGENTS.md.tmpl",
        root / "dangerous_patterns.toml": "dangerous_patterns.toml.tmpl",
        docs_dir / "session-protocol.md": "session-protocol.md.tmpl",
        docs_dir / "project-conductor.md": "project-conductor.md.tmpl",
        digests_dir / "index.md": "digest-index.md.tmpl",
        archive_dir / "README.md": "archive-readme.md.tmpl",
        root / "drifter.toml": "drifter.toml.tmpl",
    }

    # Fail closed: if any template is genuinely missing, write nothing.
    project_name = root.name or "my-project"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    contents: dict[Path, str] = {}
    missing: list[str] = []
    for dest, tmpl_name in template_files.items():
        text = template_text(tmpl_name)
        if text is None:
            missing.append(tmpl_name)
        else:
            contents[dest] = text.replace("{{PROJECT_NAME}}", project_name).replace(
                "{{NOW}}", now
            )
    if missing:
        print("\nERROR: bundled templates are missing:", file=sys.stderr)
        for tmpl_name in missing:
            print(f"  ✗ {tmpl_name}", file=sys.stderr)
        print(
            "  The Drifter installation is broken — reinstall drifter-check.",
            file=sys.stderr,
        )
        return 1

    # Optional doc stubs — only with --full
    doc_stubs: dict[Path, str] = {}
    if args.full:
        doc_stubs = {
            docs_dir / "methodology.md": _doc_stub(
                "Methodology", "constitution", "0", now
            ),
            docs_dir / "architecture.md": _doc_stub(
                "Architecture", "snapshot", "0", now
            ),
            docs_dir / "adoption-guide.md": _doc_stub(
                "Adoption Guide", "guide", "0", now
            ),
            docs_dir / "rules-reference.md": _doc_stub(
                "Rules Reference", "reference", "0", now
            ),
        }

    created = []
    skipped = []
    for dest, content in contents.items():
        if dest.exists() and not args.force:
            skipped.append(str(dest.relative_to(root)))
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        created.append(str(dest.relative_to(root)))

    # Write optional doc stubs (--full)
    for dest, content in doc_stubs.items():
        if dest.exists() and not args.force:
            skipped.append(str(dest.relative_to(root)))
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        created.append(str(dest.relative_to(root)))

    print_banner("DRIFTER INIT")
    print(f"  Root: {root}")
    mode = "full" if args.full else "minimal"
    print(f"  Mode: {mode} ({len(created)} created, {len(skipped)} skipped)")
    if not args.full:
        print("  (Run 'drifter init --full' to also create optional doc stubs)")
    if created:
        print("\n  Created:")
        for f in created:
            print(f"    ✓ {f}")
    if skipped:
        print("\n  Skipped (already exist, use --force to overwrite):")
        for f in skipped:
            print(f"    • {f}")
    print("\n  Next steps:")
    print("    1. Edit AGENTS.md with your project specifics")
    print("    2. Edit docs/session-protocol.md with your rules")
    print("    3. Edit docs/project-conductor.md with your active task")
    print("    4. Run 'drifter check' to verify")
    if skipped:
        print("\n  To refresh existing files with latest templates:")
        print("    drifter init --force")
    print_rule()
    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    config = Config.load(root=args.root)
    report = validate_docs(root=args.root, config=config)

    print_banner("DOCUMENT VALIDATION")
    print(f"  Issues: {report.total} ({report.errors} errors, {report.warns} warnings)")
    print_rule()

    if report.issues:
        print("\n  Issues found:")
        for issue in report.issues:
            print(f"    • {issue}")
    else:
        print("\n  ✓ All documents valid.")

    print_rule()
    return 1 if report.errors > 0 else 0
