"""Git workflow helpers: human commit approval and commit-message drafting."""

from __future__ import annotations

import argparse
import subprocess
from collections import Counter
from pathlib import Path


def cmd_approve(args: argparse.Namespace) -> int:
    """Arm the one-time commit approval consumed by the pre-commit hook.

    Human-only command. Agents must never run this — see the Git Boundary
    Rule in AGENTS.md.
    """
    root = Path(args.root or ".").resolve()
    git_dir = root / ".git"
    if not git_dir.exists():
        print(f"✗ Not a git repository: {root}")
        return 1

    (git_dir / "approved").touch()
    print("✓ Commit approved (one-time). Now run your `git commit`.")
    print("  The pre-commit hook consumes the approval on use.")
    return 0


_PREFIX_BY_AREA = {
    "docs": "docs",
    "tests": "test",
    "src": "feat",
    "plugins": "feat",
    ".github": "ci",
    "templates": "feat",
}


def _area(path: str) -> str:
    top = path.split("/", 1)[0]
    if top.endswith((".md", ".toml")):
        return "docs" if top.endswith(".md") else "config"
    return top


def _draft_message(staged: list[tuple[str, str]]) -> str:
    """Build a draft commit message from staged (status, path) pairs."""
    counts = Counter(status for status, _ in staged)
    areas = Counter(_area(path) for _, path in staged)

    total = len(staged)
    parts = []
    if counts.get("A"):
        parts.append(f"add {counts['A']}")
    if counts.get("M"):
        parts.append(f"update {counts['M']}")
    if counts.get("D"):
        parts.append(f"delete {counts['D']}")
    summary = ", ".join(parts) or "change"

    if len(areas) == 1:
        prefix = _PREFIX_BY_AREA.get(next(iter(areas)), "chore")
    else:
        prefix = "chore"
    subject = f"{prefix}: {summary} files ({total} total)"

    lines = [
        subject,
        "",
        "# DRAFT — generated by `drifter commit-msg` from staged changes.",
        "# Rewrite the subject to say WHY, not just WHAT.",
        "",
        "## Staged changes by area",
    ]
    for area, count in sorted(areas.items(), key=lambda kv: -kv[1]):
        lines.append(f"- {area}/: {count} file(s)")
    lines.append("")
    lines.append("## Files")
    for status, path in staged[:25]:
        lines.append(f"- [{status}] {path}")
    if total > 25:
        lines.append(f"- … and {total - 25} more")
    return "\n".join(lines)


def cmd_commit_msg(args: argparse.Namespace) -> int:
    """Draft a commit message from the staged diff (stdout, for -F -)."""
    root = Path(args.root or ".").resolve()
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-status"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(f"✗ git diff failed: {result.stderr.strip()}")
        return 1

    staged = [
        (parts[0], parts[-1])
        for line in result.stdout.splitlines()
        if (parts := line.split("\t")) and len(parts) >= 2
    ]
    if not staged:
        print("✗ Nothing staged. Run `git add` first.")
        return 1

    print(_draft_message(staged))
    return 0
